#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
android_dir="$(cd "$script_dir/.." && pwd)"

runtime_roots=(
  "$android_dir/app/src"
  "$android_dir/core"
  "$android_dir/feature"
)

forbidden_secret_pattern='sb_secret_|service_role|SUPABASE_SERVICE_ROLE_KEY|GEMINI_API_KEY|RESEND_API_KEY|BEGIN (RSA )?PRIVATE KEY|"type"[[:space:]]*:[[:space:]]*"service_account"|"private_key"[[:space:]]*:|"client_email"[[:space:]]*:'
if rg -n --glob '!**/build/**' "$forbidden_secret_pattern" "${runtime_roots[@]}"; then
  echo "Forbidden server secret marker found in Android runtime sources." >&2
  exit 1
fi

# Firebase Android Web API keys are public client configuration generated by Firebase and are
# expected to be compiled into the application. Keep the broad AIza check for accidental Gemini
# or unrelated Google API key leaks, but allow it only inside a structurally valid
# google-services.json file.
if rg -n --glob '!**/build/**' --glob '!**/google-services.json' \
  'AIza[0-9A-Za-z_-]{30,}' "${runtime_roots[@]}"; then
  echo "Google API key found outside an approved Firebase google-services.json file." >&2
  exit 1
fi

command -v python3 >/dev/null || { echo "python3 is required for Firebase config validation." >&2; exit 1; }
python3 - "${runtime_roots[@]}" <<'PY'
import json
import pathlib
import re
import sys

key_pattern = re.compile(r"AIza[0-9A-Za-z_-]{30,}")
for root in map(pathlib.Path, sys.argv[1:]):
    for path in root.rglob("google-services.json"):
        if "build" in path.parts:
            continue
        raw = path.read_text()
        document = json.loads(raw)
        forbidden = {"private_key", "private_key_id", "client_email"}
        if forbidden.intersection(document) or document.get("type") == "service_account":
            raise SystemExit(f"Service-account material is forbidden in {path}")
        configured_keys = {
            entry.get("current_key")
            for client in document.get("client", [])
            for entry in client.get("api_key", [])
            if isinstance(entry.get("current_key"), str)
        }
        discovered_keys = set(key_pattern.findall(raw))
        if not discovered_keys or discovered_keys != configured_keys:
            raise SystemExit(f"Unexpected Google API key placement in {path}")
PY

unsafe_log_pattern='printStackTrace\(|println\(|Log\.[vdiew].*(token|email|userId|uid|photo|path|response|body|\.message)'
if rg -n --glob '*.kt' --glob '!**/build/**' -i "$unsafe_log_pattern" "${runtime_roots[@]}"; then
  echo "Potential PII/server-body logging found in Android runtime sources." >&2
  exit 1
fi

if rg -n --glob 'AndroidManifest.xml' 'com\.google\.android\.gms\.permission\.AD_ID' "${runtime_roots[@]}"; then
  echo "AD_ID permission is forbidden for Android v1." >&2
  exit 1
fi

if rg -n 'firebase[-.]analytics' \
  "$android_dir/build.gradle.kts" \
  "$android_dir/app/build.gradle.kts" \
  "$android_dir/gradle/libs.versions.toml"; then
  echo "Firebase Analytics is outside Android v1 scope." >&2
  exit 1
fi

if [[ $# -gt 0 ]]; then
  apk_path="$1"
  test -f "$apk_path"
  command -v apkanalyzer >/dev/null
  permissions="$(apkanalyzer manifest permissions "$apk_path")"
  if grep -q 'com.google.android.gms.permission.AD_ID' <<<"$permissions"; then
    echo "Merged APK unexpectedly contains AD_ID permission." >&2
    exit 1
  fi
fi

echo "Android source secret, PII-log and AD_ID scan passed."
