// Sealed runtime artifact read back from production analyze v140 on 2026-08-01.
// Its source hash is bound to approval record RD-SPR-20260801-3A68229B.
// Do not regenerate this file from unapproved draft sources.
// Generated by scripts/generate_localization_profiles.mjs.
// Do not edit manually. Source SHA-256: 3a68229b1860572ff70600287412d3dadf890597698acfc3edb23afc8b9c6932

export const safetyProfileManifestVersion = 1 as const;
export const safetyProfileSourceSHA256 =
  "3a68229b1860572ff70600287412d3dadf890597698acfc3edb23afc8b9c6932" as const;
export const safetyProfileReviewStatus = "machine_draft" as const;

export const appLanguages = ["tr", "en"] as const;
export type AppLanguage = (typeof appLanguages)[number];

export const contentLocales = [
  "tr-TR",
  "en-001",
  "en-GB",
  "en-US",
  "en-AU",
  "en-CA",
] as const;
export type ContentLocale = (typeof contentLocales)[number];

export const jurisdictionCountries = [
  "TR",
  "INTL",
  "GB",
  "US",
  "AU",
  "CA",
] as const;
export type JurisdictionCountry = (typeof jurisdictionCountries)[number];

export const legalDocumentSetIDs = ["tr-current", "en-global-v1"] as const;
export type LegalDocumentSetID = (typeof legalDocumentSetIDs)[number];

export const riskMethods = ["fine_kinney", "matrix_5x5"] as const;
export type RiskMethod = (typeof riskMethods)[number];

export const safetyProfileIDs = [
  "tr-tr-current-v1",
  "en-intl-generic-v1",
  "en-gb-generic-v1",
  "en-us-generic-v1",
  "en-au-generic-v1",
  "en-ca-generic-v1",
] as const;
export type SafetyProfileID = (typeof safetyProfileIDs)[number];

export type RegulatoryReferencePolicy =
  | "tr_current"
  | "none"
  | "explicit_question_only";

export const defaultSafetyProfileID: SafetyProfileID = "tr-tr-current-v1";
export const englishFallbackSafetyProfileID: SafetyProfileID =
  "en-intl-generic-v1";

export const hierarchyOfControls = [
  "elimination",
  "substitution",
  "engineering controls",
  "administrative controls",
  "personal protective equipment (PPE)",
] as const;
export const riskMethodDisclaimer = {
  "semantic_key": "risk_method.legal_standard_disclaimer",
  "review_status": "machine_draft",
  "tr":
    "Fine-Kinney ve 5×5, riskleri önceliklendirmeye yardımcı olan ürün yöntemleridir; hukuki standart veya mevzuata uygunluk kanıtı değildir.",
  "en":
    "Fine-Kinney and 5×5 are product methods for prioritising risk; they are not legal standards or evidence of regulatory compliance.",
} as const;
export const riskBandDrafts = {
  "fine_kinney": [
    "Intolerable",
    "High",
    "Substantial",
    "Possible",
    "Trivial",
  ],
  "matrix_5x5": [
    "Intolerable",
    "High",
    "Medium",
    "Low",
    "Trivial",
  ],
} as const;

export const safetyProfiles = [
  {
    "id": "tr-tr-current-v1",
    "language": "tr",
    "content_locale": "tr-TR",
    "jurisdiction_country": "TR",
    "jurisdiction_region": null,
    "status": "current_regulatory",
    "review_status": "machine_draft",
    "display_name_key": "safety_profile.turkey",
    "primary_product_term": "iş güvenliği risk analizi",
    "primary_domain_term": "iş sağlığı ve güvenliği",
    "finding_term": "bulgu",
    "hazard_term": "tehlike",
    "risk_assessment_term": "risk değerlendirmesi",
    "control_term": "kontrol tedbiri",
    "corrective_action_term": "düzeltici faaliyet",
    "default_risk_method": "fine_kinney",
    "allowed_risk_methods": [
      "fine_kinney",
      "matrix_5x5",
    ],
    "legislation_canvas_enabled": true,
    "structured_regulatory_references_enabled": true,
    "regulatory_reference_policy": "tr_current",
    "legal_compliance_claims_allowed": false,
    "spelling_style": "turkish",
    "prompt_directives": [
      "Mevcut Türkçe analiz ve rapor davranışını koru.",
      "Yalnız görüntüde gözlenebilen kanıta dayan; görünmeyen ölçüm veya maruziyet sonucu uydurma.",
      "Risk skorunu hukukî uygunluk skoru olarak sunma.",
    ],
    "profile_version": 1,
    "forbidden_terms": [
      "guarantees legal compliance",
      "certifies legal compliance",
      "replaces a professional inspection",
      "officially approved",
      "zero risk guaranteed",
      "kesin uyumluluk",
      "kesin mevzuata uygundur",
      "hukukî uygunluğu garanti eder",
      "resmî denetim yerine geçer",
    ],
  },
  {
    "id": "en-intl-generic-v1",
    "language": "en",
    "content_locale": "en-001",
    "jurisdiction_country": "INTL",
    "jurisdiction_region": null,
    "status": "terminology_only",
    "review_status": "machine_draft",
    "display_name_key": "safety_profile.international",
    "primary_product_term": "safety inspection",
    "primary_domain_term": "workplace safety",
    "finding_term": "finding",
    "hazard_term": "hazard",
    "risk_assessment_term": "risk assessment",
    "control_term": "control measure",
    "corrective_action_term": "corrective action",
    "default_risk_method": "matrix_5x5",
    "allowed_risk_methods": [
      "matrix_5x5",
      "fine_kinney",
    ],
    "legislation_canvas_enabled": false,
    "structured_regulatory_references_enabled": false,
    "regulatory_reference_policy": "none",
    "legal_compliance_claims_allowed": false,
    "spelling_style": "international",
    "prompt_directives": [
      "Use neutral international workplace-safety terminology.",
      "Prefer the hierarchy of controls and on-site verification language.",
      "Do not name a regulator or infer legal compliance from a photograph.",
    ],
    "profile_version": 1,
    "forbidden_terms": [
      "guarantees legal compliance",
      "certifies legal compliance",
      "replaces a professional inspection",
      "officially approved",
      "zero risk guaranteed",
      "global compliance",
      "OSHA compliant",
      "HSE compliant",
      "WHS compliant",
      "Canadian OHS compliant",
      "6331 compliant",
    ],
  },
  {
    "id": "en-gb-generic-v1",
    "language": "en",
    "content_locale": "en-GB",
    "jurisdiction_country": "GB",
    "jurisdiction_region": null,
    "status": "terminology_only",
    "review_status": "machine_draft",
    "display_name_key": "safety_profile.united_kingdom",
    "primary_product_term": "risk assessment",
    "primary_domain_term": "health and safety",
    "finding_term": "finding",
    "hazard_term": "hazard",
    "risk_assessment_term": "risk assessment",
    "control_term": "control measure",
    "corrective_action_term": "corrective action",
    "default_risk_method": "matrix_5x5",
    "allowed_risk_methods": [
      "matrix_5x5",
      "fine_kinney",
    ],
    "legislation_canvas_enabled": false,
    "structured_regulatory_references_enabled": false,
    "regulatory_reference_policy": "none",
    "legal_compliance_claims_allowed": false,
    "spelling_style": "british",
    "prompt_directives": [
      "Use UK health and safety, risk assessment and control-measure terminology.",
      "Use British spelling such as prioritise and organised.",
      "Do not imply HSE or HSENI approval, certification or legal compliance.",
    ],
    "profile_version": 1,
    "forbidden_terms": [
      "guarantees legal compliance",
      "certifies legal compliance",
      "replaces a professional inspection",
      "officially approved",
      "zero risk guaranteed",
      "HSE compliant",
      "HSENI compliant",
      "OSHA compliant",
      "WHS Act compliant",
      "6331 compliant",
    ],
  },
  {
    "id": "en-us-generic-v1",
    "language": "en",
    "content_locale": "en-US",
    "jurisdiction_country": "US",
    "jurisdiction_region": null,
    "status": "terminology_only",
    "review_status": "machine_draft",
    "display_name_key": "safety_profile.united_states",
    "primary_product_term": "safety inspection",
    "primary_domain_term": "occupational safety and health",
    "finding_term": "finding",
    "hazard_term": "hazard",
    "risk_assessment_term": "hazard assessment",
    "control_term": "control",
    "corrective_action_term": "corrective action",
    "default_risk_method": "matrix_5x5",
    "allowed_risk_methods": [
      "matrix_5x5",
      "fine_kinney",
    ],
    "legislation_canvas_enabled": false,
    "structured_regulatory_references_enabled": false,
    "regulatory_reference_policy": "none",
    "legal_compliance_claims_allowed": false,
    "spelling_style": "american",
    "prompt_directives": [
      "Use U.S. occupational safety and health, hazard assessment and corrective-action terminology.",
      "Use American spelling such as prioritize and organized.",
      "Do not call a photo inspection a JHA or JSA without a separate task-based workflow.",
    ],
    "profile_version": 1,
    "forbidden_terms": [
      "guarantees legal compliance",
      "certifies legal compliance",
      "replaces a professional inspection",
      "officially approved",
      "zero risk guaranteed",
      "OSHA compliant",
      "OSHA violation",
      "citation-ready",
      "JHA completed",
      "JSA completed",
      "HSE compliant",
      "WHS Act compliant",
      "6331 compliant",
    ],
  },
  {
    "id": "en-au-generic-v1",
    "language": "en",
    "content_locale": "en-AU",
    "jurisdiction_country": "AU",
    "jurisdiction_region": null,
    "status": "terminology_only",
    "review_status": "machine_draft",
    "display_name_key": "safety_profile.australia",
    "primary_product_term": "WHS inspection",
    "primary_domain_term": "work health and safety",
    "finding_term": "finding",
    "hazard_term": "hazard",
    "risk_assessment_term": "risk assessment",
    "control_term": "control measure",
    "corrective_action_term": "corrective action",
    "default_risk_method": "matrix_5x5",
    "allowed_risk_methods": [
      "matrix_5x5",
      "fine_kinney",
    ],
    "legislation_canvas_enabled": false,
    "structured_regulatory_references_enabled": false,
    "regulatory_reference_policy": "none",
    "legal_compliance_claims_allowed": false,
    "spelling_style": "australian",
    "prompt_directives": [
      "Use Australian WHS, workplace-inspection and control-measure terminology.",
      "Use Australian spelling such as prioritise and organised.",
      "Do not treat model WHS laws as a single national legal compliance profile.",
    ],
    "profile_version": 1,
    "forbidden_terms": [
      "guarantees legal compliance",
      "certifies legal compliance",
      "replaces a professional inspection",
      "officially approved",
      "zero risk guaranteed",
      "Australian law compliant",
      "WHS compliant",
      "model WHS law compliant",
      "OSHA compliant",
      "HSE compliant",
      "6331 compliant",
    ],
  },
  {
    "id": "en-ca-generic-v1",
    "language": "en",
    "content_locale": "en-CA",
    "jurisdiction_country": "CA",
    "jurisdiction_region": null,
    "status": "terminology_only",
    "review_status": "machine_draft",
    "display_name_key": "safety_profile.canada",
    "primary_product_term": "OHS inspection",
    "primary_domain_term": "occupational health and safety",
    "finding_term": "finding",
    "hazard_term": "hazard",
    "risk_assessment_term": "hazard assessment",
    "control_term": "control measure",
    "corrective_action_term": "corrective action",
    "default_risk_method": "matrix_5x5",
    "allowed_risk_methods": [
      "matrix_5x5",
      "fine_kinney",
    ],
    "legislation_canvas_enabled": false,
    "structured_regulatory_references_enabled": false,
    "regulatory_reference_policy": "none",
    "legal_compliance_claims_allowed": false,
    "spelling_style": "canadian",
    "prompt_directives": [
      "Use Canadian OHS, hazard-assessment and workplace-inspection terminology.",
      "Use Canadian spelling and neutral wording across federal, provincial and territorial contexts.",
      "Do not imply a single Canada-wide OHS legal compliance determination.",
    ],
    "profile_version": 1,
    "forbidden_terms": [
      "guarantees legal compliance",
      "certifies legal compliance",
      "replaces a professional inspection",
      "officially approved",
      "zero risk guaranteed",
      "Canadian compliance",
      "Canadian OHS compliant",
      "Canada-wide OHS compliant",
      "OSHA compliant",
      "HSE compliant",
      "WHS Act compliant",
      "6331 compliant",
    ],
  },
] as const;
export type SafetyProfileDefinition = (typeof safetyProfiles)[number];

export interface LocalizationContext {
  app_language: AppLanguage;
  output_language: AppLanguage;
  output_locale: ContentLocale;
  work_jurisdiction_country: JurisdictionCountry;
  work_jurisdiction_region: string | null;
  safety_profile_id: SafetyProfileID;
  safety_profile_version: number;
  method: RiskMethod;
  legal_document_set: LegalDocumentSetID;
}

export interface LocalizationSnapshot {
  context: LocalizationContext;
  regulatory_reference_policy: RegulatoryReferencePolicy;
  prompt_profile_version: number;
}

const safetyProfileByID = new Map<SafetyProfileID, SafetyProfileDefinition>(
  safetyProfiles.map((profile) => [profile.id, profile]),
);

export function isSafetyProfileID(value: unknown): value is SafetyProfileID {
  return typeof value === "string" &&
    (safetyProfileIDs as readonly string[]).includes(value);
}

export function getSafetyProfile(id: SafetyProfileID): SafetyProfileDefinition {
  const profile = safetyProfileByID.get(id);
  if (!profile) {
    throw new Error("safety_profile_manifest_incomplete");
  }
  return profile;
}
