import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {ROOT} from './lib.mjs';
import {verifyLocalSessionToken} from './auth_session_probe.mjs';
import {probeP05Profile,p05ProfileFiles} from './p05_profile_probe.mjs';
export const p05AccountPilotFiles=['supabase/migrations/20260913193231_isg_p05_account_pilot_creation.sql','scripts/isg/p05_account_pilot_probe.mjs',...p05ProfileFiles];
const q=v=>"'"+String(v).replaceAll("'","''")+"'";
export async function beginP05AccountPilotProbe({synthetic,sql,concurrentSql,token,secret,ownerID,companyID,request,waitReady,pass}) {
  if(synthetic!==true)throw Error('AUTH_RESTORE_ACCOUNT_PILOT_SYNTHETIC_REQUIRED');
  const claims=verifyLocalSessionToken(token,secret);
  if(claims.sub!==ownerID||!companyID)throw Error('AUTH_RESTORE_ACCOUNT_PILOT_SCOPE_REQUIRED');
  const mark=(id,ok)=>pass('p05_account_pilot_'+id,ok);
  const rpc=(name,body)=>request('/rpc/'+name,{method:'POST',body});
  const availability=(company=null)=>rpc('isg_workspace_availability_v1',{p_company:company});
  const create=(mutation=randomUUID(),name='Pilot Yeni Firma')=>rpc('isg_pilot_company_create_v1',{p_mutation:mutation,p_name:name,p_hazard_class:'high'});
  const blocked=r=>r.status===400&&r.body.message==='FEATURE_UNAVAILABLE';
  const legacy=()=>sql("SELECT md5(to_jsonb(c)::text) FROM public.companies c WHERE id="+q(companyID)+";SELECT md5(pg_get_functiondef('private.company_limit_for_user(uuid)'::regprocedure)||pg_get_functiondef('private.enforce_company_write_rules()'::regprocedure));");
  const before=legacy();
  sql(readFileSync(`${ROOT}/${p05AccountPilotFiles[0]}`,'utf8'));
  await waitReady(()=>create().status!==404);
  mark('empty_account_roster_and_closed_rollout',sql("SELECT (SELECT count(*)=0 FROM private_isg.p05_pilot_accounts) AND (SELECT NOT read_enabled AND NOT write_enabled FROM private_isg.rollout WHERE feature='personnel');")==='t');
  sql("UPDATE private_isg.rollout SET read_enabled=true,write_enabled=true WHERE feature='personnel';");
  mark('global_flags_do_not_admit_unlisted_account',blocked(create())&&availability().body.can_read===false);
  sql("INSERT INTO private_isg.p05_pilot_accounts(actor_id,read_enabled,approved_reference,expires_at) VALUES("+q(ownerID)+",true,'synthetic-approval',clock_timestamp()+interval '1 hour');");
  mark('account_can_enter_without_preselected_company',availability().body.can_read===true&&availability().body.can_write===false);
  mark('read_only_account_cannot_create',blocked(create()));
  sql("UPDATE private_isg.p05_pilot_accounts SET write_enabled=true WHERE actor_id="+q(ownerID)+";");
  const mutation=randomUUID();
  const first=create(mutation);
  mark('create_uses_authenticated_owner',first.status===200&&first.body.company.user_id===ownerID&&first.body.replayed===false);
  const company=first.body.company.id;
  mark('new_company_origin_grant_default_are_atomic',sql("SELECT (SELECT count(*) FROM private_isg.p05_pilot_company_origins WHERE company_id="+q(company)+")=1 AND (SELECT count(*) FROM private_isg.p05_pilot_grants WHERE company_id="+q(company)+")=1 AND (SELECT count(*) FROM private_isg.workplaces WHERE legacy_company_id="+q(company)+")=1;")==='t');
  mark('same_mutation_returns_same_company',create(mutation).body.company.id===company&&create(mutation).body.replayed===true);
  mark('changed_retry_is_conflict',create(mutation,'Farklı Firma').body.message==='IDEMPOTENCY_CONFLICT');
  const concurrent=await Promise.all(Array.from({length:3},()=>concurrentSql("BEGIN;SET LOCAL ROLE authenticated;SELECT set_config('request.jwt.claims',"+q(JSON.stringify(claims))+",true) IS NOT NULL;SELECT public.isg_pilot_company_create_v1("+q(mutation)+",'Pilot Yeni Firma','high');COMMIT;")));
  mark('concurrent_retry_has_one_company',concurrent.every(r=>r.ok&&JSON.parse(r.output.split('\n').at(-1)).company.id===company)&&sql("SELECT count(*) FROM private_isg.p05_pilot_company_origins WHERE actor_id="+q(ownerID)+" AND mutation_id="+q(mutation)+";")==='1');
  mark('new_company_is_writable_old_company_hidden',availability(company).body.can_write===true&&availability(companyID).body.can_read===false);
  sql("INSERT INTO private_isg.p05_pilot_grants(actor_id,company_id,approved_reference,expires_at) VALUES("+q(ownerID)+","+q(companyID)+",'synthetic-approval',clock_timestamp()+interval '1 hour');");
  mark('manual_company_grant_cannot_adopt_old_company',availability(companyID).body.can_read===false);
  const personArgs={p_company:company,p_action:'create',p_operation:randomUUID(),p_mutation:randomUUID(),p_employee:null,p_expected:0,p_name:'Pilot Personel',p_change_department:true,p_department:null,p_department_name:null};
  const person=rpc('isg_personnel_mutate_v1',personArgs);
  mark('personnel_create_commits_in_new_company',person.status===200&&person.body.company_id===company&&person.body.owner_id===ownerID);
  await probeP05Profile({synthetic,sql,rpc,ownerID,oldCompanyID:companyID,waitReady,pass});
  mark('directory_create_commits_in_new_company',rpc('isg_directory_mutate_v1',{p_company:company,p_kind:'jobs',p_operation:randomUUID(),p_mutation:randomUUID(),p_id:null,p_expected:0,p_body:{name:'Pilot Görev',code:'PILOT-JOB',description:null,is_archived:false}}).status===200);
  mark('old_company_mutation_rejected',blocked(rpc('isg_personnel_mutate_v1',{...personArgs,p_company:companyID})));
  const subscription=sql("SELECT current_period_ends_at FROM public.user_subscriptions WHERE user_id="+q(ownerID)+";");
  sql("UPDATE public.user_subscriptions SET current_period_ends_at=clock_timestamp()-interval '1 day' WHERE user_id="+q(ownerID)+";");
  mark('pilot_does_not_override_paid_plan',create().body.message==='PAID_PLAN_REQUIRED'&&availability(company).body.can_read===true&&availability(company).body.can_write===false);
  sql("UPDATE public.user_subscriptions SET current_period_ends_at="+(subscription?q(subscription):'NULL')+" WHERE user_id="+q(ownerID)+";");
  sql("UPDATE private_isg.p05_pilot_accounts SET write_enabled=false WHERE actor_id="+q(ownerID)+";");
  mark('account_write_pause_blocks_new_writes_and_receipt_replay',blocked(create(mutation))&&blocked(rpc('isg_personnel_mutate_v1',personArgs))&&availability(company).body.can_read===true);
  sql("UPDATE private_isg.p05_pilot_accounts SET write_enabled=true,revoked_at=clock_timestamp() WHERE actor_id="+q(ownerID)+";");
  mark('account_revocation_is_immediate',blocked(create())&&availability(company).body.can_read===false);
  sql("UPDATE private_isg.p05_pilot_accounts SET revoked_at=NULL,created_at=clock_timestamp()-interval '2 days',expires_at=clock_timestamp()-interval '1 day' WHERE actor_id="+q(ownerID)+";");
  mark('expired_account_cannot_use_unexpired_company_grant',blocked(create())&&availability(company).body.can_read===false);
  sql("UPDATE private_isg.p05_pilot_accounts SET created_at=clock_timestamp(),expires_at=clock_timestamp()+interval '1 hour' WHERE actor_id="+q(ownerID)+";");
  const legacyCompany=sql("INSERT INTO public.companies(user_id,name,hazard_class) VALUES("+q(ownerID)+",'Legacy Yol Yeni Firma','medium') RETURNING id;");
  mark('legacy_create_does_not_auto_enroll_or_bootstrap',availability(legacyCompany).body.can_read===false&&sql("SELECT NOT EXISTS(SELECT 1 FROM private_isg.workplaces WHERE company_id="+q(legacyCompany)+");")==='t');
  mark('client_cannot_choose_owner_or_existing_company',rpc('isg_pilot_company_create_v1',{p_mutation:randomUUID(),p_name:'B',p_hazard_class:'high',p_company:companyID,p_owner:ownerID}).status>=400);
  mark('legacy_rows_and_write_rules_unchanged',legacy()===before);
  mark('private_tables_not_client_writable',sql("SELECT NOT has_table_privilege('authenticated','private_isg.p05_pilot_accounts','INSERT') AND NOT has_table_privilege('authenticated','private_isg.p05_pilot_company_origins','INSERT') AND NOT has_function_privilege('service_role','public.isg_pilot_company_create_v1(uuid,text,text)','EXECUTE');")==='t');
  mark('new_rpc_public_invoker_private_checked_definer',sql("SELECT NOT (SELECT prosecdef FROM pg_proc WHERE oid='public.isg_pilot_company_create_v1(uuid,text,text)'::regprocedure) AND (SELECT prosecdef AND proconfig @> ARRAY['search_path=\"\"'] FROM pg_proc WHERE oid='private_isg.p05_pilot_create_company(uuid,text,text)'::regprocedure);")==='t');
  sql("UPDATE private_isg.rollout SET read_enabled=false,write_enabled=false WHERE feature='personnel';");
  mark('global_kill_blocks_new_and_existing_pilot_work',blocked(create())&&blocked(rpc('isg_personnel_mutate_v1',personArgs))&&availability(company).body.can_read===false);
  sql('DELETE FROM private_isg.p05_pilot_grants;DELETE FROM private_isg.p05_pilot_accounts;');
  return {afterLogout(){mark('logged_out_account_cannot_create',create().status===403);return{production_deployed:false,native_connected:false,account_allowlist:true,server_created_company_scope:true,legacy_quotas_preserved:true};}};
}
