from pathlib import Path
import re
root=Path(__file__).resolve().parents[2]
core=(root/'supabase/migrations/20260913230000_isg_module_core.sql').read_text()
tables=['emergency_plan_versions','drill_records','appointments','ppe_handovers','ppe_returns']
functions=['publish_emergency_plan','plan_drill','record_drill_result','record_appointment','end_appointment','record_ppe_handover','record_ppe_return']
parts=["-- Scoped pilot operational modules. Generated by scripts/modules/build_pilot.py.\n-- File assets are unavailable in this pilot: UUID slots must remain NULL. No file upload is claimed.\nSET LOCAL lock_timeout='5s';\nCREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA extensions;\nSET LOCAL search_path=public,extensions;\n"]
for name in tables:
 s=re.search(r'CREATE TABLE private_isg\.'+name+r' \([\s\S]*?\n\);',core).group()
 s=s.replace('uuid REFERENCES private_isg.file_assets(asset_id)', 'uuid CHECK ('+('evidence_asset_id' if name=='ppe_handovers' else 'asset_id')+' IS NULL)')
 parts += [s,f'ALTER TABLE private_isg.{name} ENABLE ROW LEVEL SECURITY;',f'REVOKE ALL ON private_isg.{name} FROM PUBLIC,anon,authenticated,service_role;']
for m in re.finditer(r'CREATE (?:UNIQUE )?INDEX [^;]+;',core):
 if any('ON private_isg.'+name+'(' in m.group() for name in tables): parts.append(m.group())
for name in functions:
 s=re.search(r'CREATE FUNCTION private_isg\.'+name+r'\([\s\S]*?END \$\$;',core).group()
 s=re.sub(r"  IF p_asset IS NOT NULL THEN[\s\S]*?\n  END IF;", "  IF p_asset IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE='P0001',MESSAGE='FILE_STORAGE_UNAVAILABLE'; END IF;",s)
 parts.append(s)
 params=s.split('(',1)[1].split(') RETURNS')[0]
 types=','.join(p.strip().split()[1] for p in params.split(','))
 parts.append(f'REVOKE ALL ON FUNCTION private_isg.{name}({types}) FROM PUBLIC,anon,authenticated,service_role;')
for file in ['20260915130000_isg_emergency_plans.sql','20260915150000_isg_drills.sql','20260915170000_isg_ppe_handovers.sql','20260915190000_isg_appointments.sql']:
 s=(root/'supabase/migrations'/file).read_text()
 s=re.sub(r'^BEGIN;\s*','',s,flags=re.M);s=re.sub(r'^COMMIT;\s*','',s,flags=re.M)
 # Every account-level read and every write starts through this guard.
 s=s.replace('DECLARE actor uuid:=private_isg.active_actor();\nBEGIN','''DECLARE actor uuid:=private_isg.active_actor();
BEGIN
  IF NOT private_isg.p05_pilot_account_enabled(actor,p_write) THEN
    RAISE EXCEPTION USING ERRCODE='P0001',MESSAGE='FEATURE_UNAVAILABLE'; END IF;
  IF p_company IS NOT NULL AND NOT private_isg.p05_pilot_can_read(actor,p_company) THEN
    RAISE EXCEPTION USING ERRCODE='P0001',MESSAGE='ACCESS_DENIED'; END IF;''')
 s=s.replace('WHERE c.user_id=actor AND NOT c.is_archived','WHERE c.user_id=actor AND NOT c.is_archived AND private_isg.p05_pilot_can_read(actor,c.id)')
 s=s.replace("AT TIME ZONE 'UTC'", "AT TIME ZONE 'Europe/Istanbul'")
 parts.append(s)
for name in re.findall(r'CREATE TABLE private_isg\.([a-z_]+)', '\n'.join(parts)):
 parts.append(f'REVOKE ALL ON private_isg.{name} FROM PUBLIC,anon,authenticated,service_role;')
# Keep switches closed until deployment readback and explicit activation DML.
parts.append("NOTIFY pgrst,'reload schema';")
output=root/'supabase/migrations/20260914204842_isg_pilot_operational_modules.sql'
output.write_text('\n\n'.join(parts)+'\n')
print(output)
