BEGIN;
SELECT set_config('test.actor','20000000-0000-0000-0000-000000000001',true);
UPDATE private_isg.rollout SET read_enabled=true,write_enabled=true WHERE feature IN ('modules','nonconformity');
UPDATE private_isg.module_registry SET read_enabled=true,write_enabled=true;
CREATE FUNCTION pg_temp.workflow_check(action text,payload jsonb) RETURNS jsonb LANGUAGE sql AS $$ SELECT public.isg_checklists_mutate_v1('10000000-0000-0000-0000-000000000001',action,gen_random_uuid(),gen_random_uuid(),payload) $$;
DO $$ DECLARE co uuid:='10000000-0000-0000-0000-000000000001'; wp uuid:='40000000-0000-0000-0000-000000000001'; actor uuid:='20000000-0000-0000-0000-000000000001'; code text; run uuid; plan uuid; meeting uuid; r jsonb; activity_id_ uuid; BEGIN
code:=pg_temp.workflow_check('draft_template','{"title":"Workflow integration check"}')->'answer'->>'template_code';
PERFORM pg_temp.workflow_check('set_item',jsonb_build_object('template_code',code,'version',1,'item_code','q1','prompt','Kontrol sorusu','position',1,'allows_not_applicable',true));
PERFORM pg_temp.workflow_check('publish_template',jsonb_build_object('template_code',code,'version',1,'approval_note','Uzman tarafından hazırlanan test listesi'));
run:=(pg_temp.workflow_check('start_run',jsonb_build_object('workplace_id',wp,'template_code',code))->>'run_id')::uuid;
IF jsonb_array_length(public.isg_pilot_process_references_v1('checklist_run',co,NULL,NULL,0)->'rows')<>0 THEN RAISE EXCEPTION 'Open run offered as completed';END IF;
PERFORM pg_temp.workflow_check('record_item',jsonb_build_object('run_id',run,'item_code','q1','result','conform'));
PERFORM pg_temp.workflow_check('submit_run',jsonb_build_object('run_id',run));
IF public.isg_pilot_process_references_v1('checklist_run',co,run,NULL,0)->'rows'->0->'values'->>'state' IS DISTINCT FROM 'submitted' THEN RAISE EXCEPTION 'Completed run absent';END IF;
INSERT INTO private_isg.annual_work_plans(company_id,owner_id,workplace_id,plan_year) VALUES(co,actor,wp,extract(year FROM current_date-1)::integer) RETURNING plan_id INTO plan;
r:=public.isg_pilot_process_mutate_v1(co,'save',gen_random_uuid(),gen_random_uuid(),jsonb_build_object('kind','annual_work_item','related_kind','checklist_run','related_id',run,'values',jsonb_build_object('plan_id',plan,'activity','Kontrol faaliyeti','planned_on',current_date-1,'state','planned')));
activity_id_:=(r->>'id')::uuid;
IF r->'values'->>'state' IS DISTINCT FROM 'planned' THEN RAISE EXCEPTION 'Link auto completed activity';END IF;
r:=private_isg.process_row('annual_work_plan',plan);
IF r->'child_summary'->>'open' IS DISTINCT FROM '1' OR r->'child_summary'->>'overdue' IS DISTINCT FROM '1' THEN RAISE EXCEPTION 'Plan child summary mismatch';END IF;
UPDATE private_isg.annual_work_plan_items SET state='performed',performed_on=current_date WHERE item_id=activity_id_;
IF private_isg.process_row('annual_work_plan',plan)->'child_summary'->>'open' IS DISTINCT FROM '0' THEN RAISE EXCEPTION 'Plan completion not reflected';END IF;
INSERT INTO private_isg.board_meetings(company_id,owner_id,workplace_id,applicability,counts_towards_legal_score,planned_on,agenda) VALUES(co,actor,wp,'voluntary',false,current_date,'["Test gündemi"]') RETURNING meeting_id INTO meeting;
PERFORM public.isg_pilot_process_mutate_v1(co,'save',gen_random_uuid(),gen_random_uuid(),jsonb_build_object('kind','board_decision','related_kind','checklist_run','related_id',run,'values',jsonb_build_object('meeting_id',meeting,'decision_no',1,'decision_text','Kontrol sonrası takip','due_on',current_date-1,'state','open')));
IF private_isg.process_row('board',meeting)->'child_summary'->>'overdue' IS DISTINCT FROM '1' THEN RAISE EXCEPTION 'Board child summary mismatch';END IF;
IF jsonb_array_length(public.isg_pilot_module_tracking_v1(co)->'rows')<>13 THEN RAISE EXCEPTION 'Checklist tracking missing';END IF;
BEGIN PERFORM public.isg_pilot_process_references_v1('checklist_run','10000000-0000-0000-0000-000000000002',run,NULL,0);RAISE EXCEPTION 'Foreign scope allowed';EXCEPTION WHEN SQLSTATE 'P0001' THEN IF SQLERRM IS DISTINCT FROM 'ACCESS_DENIED' THEN RAISE;END IF;END;
RAISE NOTICE 'ok checklist start/answer/submit/reference/plan/board/derived workload/no auto completion/owner';
END $$;
ROLLBACK;
