BEGIN;
SELECT set_config('test.actor','20000000-0000-0000-0000-000000000001',true);
SELECT set_config('test.pilot','true',true);
SELECT set_config('test.pilot_write','true',true);
UPDATE private_isg.rollout SET read_enabled=true,write_enabled=true;
UPDATE private_isg.module_registry SET read_enabled=true,write_enabled=true;
DO $$ DECLARE op uuid:=gen_random_uuid(); m uuid:=gen_random_uuid(); payload jsonb; r jsonb; again jsonb; id uuid; listing jsonb; BEGIN
 payload:=jsonb_build_object('title','Kişisel PDF','category','other','file_name','test.pdf','note','Özel not','extension','pdf','bytes',42,'sha256',repeat('b',64),'tags',jsonb_build_array('Kişisel'));
 r:=public.isg_pilot_file_library_mutate_v2(NULL,'open_upload',op,m,payload); id:=(r->>'entry_id')::uuid;
 again:=public.isg_pilot_file_library_mutate_v2(NULL,'open_upload',op,m,payload);
 IF r->'row' IS DISTINCT FROM again->'row' OR r->'row'->>'company_id' IS NOT NULL THEN RAISE EXCEPTION 'personal replay/scope'; END IF;
 listing:=public.isg_pilot_file_library_read_v2(NULL,'list','Kişisel',NULL,NULL,NULL,30,0);
 IF jsonb_array_length(listing->'rows')<>1 OR listing->'companies'<>'[]'::jsonb THEN RAISE EXCEPTION 'personal all-files read %',listing; END IF;
 IF jsonb_array_length(public.isg_pilot_file_library_read_v2('10000000-0000-0000-0000-000000000001','list',NULL,NULL,NULL,NULL,30,0)->'rows')<>0 THEN RAISE EXCEPTION 'personal leaked into company'; END IF;
 IF public.isg_pilot_file_sources_v1(id)<>'[]'::jsonb THEN RAISE EXCEPTION 'personal source'; END IF;
 payload:=jsonb_build_object('entry_id',id,'expected_version',1,'title','Düzenlenen kişisel dosya','note','Yeni not');
 r:=public.isg_pilot_file_library_mutate_v2(NULL,'rename_entry',gen_random_uuid(),gen_random_uuid(),payload);
 IF r->'row'->>'note'<>'Yeni not' THEN RAISE EXCEPTION 'personal edit'; END IF;
 BEGIN PERFORM public.isg_pilot_file_library_mutate_v2('10000000-0000-0000-0000-000000000001','archive_entry',gen_random_uuid(),gen_random_uuid(),jsonb_build_object('entry_id',id,'expected_version',2)); RAISE EXCEPTION 'scope substitution'; EXCEPTION WHEN SQLSTATE 'P0001' THEN IF SQLERRM<>'ACCESS_DENIED' THEN RAISE; END IF; END;
 PERFORM set_config('test.actor','20000000-0000-0000-0000-000000000002',true);
 IF jsonb_array_length(public.isg_pilot_file_library_read_v2(NULL,'list',NULL,NULL,NULL,NULL,30,0)->'rows')<>0 THEN RAISE EXCEPTION 'cross-owner list'; END IF;
 BEGIN PERFORM public.isg_pilot_file_library_read_v2(NULL,'detail',NULL,NULL,NULL,id,30,0); RAISE EXCEPTION 'cross-owner detail'; EXCEPTION WHEN SQLSTATE 'P0001' THEN IF SQLERRM<>'ACCESS_DENIED' THEN RAISE; END IF; END;
 BEGIN PERFORM public.isg_pilot_file_library_mutate_v2(NULL,'rename_entry',gen_random_uuid(),gen_random_uuid(),payload); RAISE EXCEPTION 'cross-owner write'; EXCEPTION WHEN SQLSTATE 'P0001' THEN IF SQLERRM<>'ACCESS_DENIED' THEN RAISE; END IF; END;
 PERFORM set_config('test.actor','20000000-0000-0000-0000-000000000001',true);
 UPDATE public.user_subscriptions SET status='expired' WHERE user_id=private_isg.active_actor();
 BEGIN PERFORM public.isg_pilot_file_library_mutate_v2(NULL,'rename_entry',gen_random_uuid(),gen_random_uuid(),payload); RAISE EXCEPTION 'unpaid personal write'; EXCEPTION WHEN SQLSTATE 'P0001' THEN IF SQLERRM<>'PAID_PLAN_REQUIRED' THEN RAISE; END IF; END;
 UPDATE public.user_subscriptions SET status='active' WHERE user_id=private_isg.active_actor();
 PERFORM public.isg_pilot_file_library_mutate_v2(NULL,'archive_entry',gen_random_uuid(),gen_random_uuid(),jsonb_build_object('entry_id',id,'expected_version',2));
 IF jsonb_array_length(public.isg_pilot_file_library_read_v2(NULL,'list',NULL,NULL,NULL,NULL,30,0)->'rows')<>0 THEN RAISE EXCEPTION 'personal archive'; END IF;
 PERFORM set_config('test.pilot','false',true);
 BEGIN PERFORM public.isg_pilot_file_library_read_v2(NULL,'list',NULL,NULL,NULL,NULL,30,0); RAISE EXCEPTION 'nonpilot read'; EXCEPTION WHEN SQLSTATE 'P0001' THEN IF SQLERRM<>'ACCESS_DENIED' THEN RAISE; END IF; END;
 RAISE NOTICE 'ok personal files / account ownership / company isolation / replay / edit / archive / paid and pilot gates';
END $$;
ROLLBACK;
