"""İSGADA catalogue authoring. One effective definition per key; build outputs are generated."""
QUESTIONS = [('Q01',
  'scope',
  'Firma bilgisi eklemek ister misiniz?',
  'optional_scope',
  'Firma seçmeden devam edebilirsiniz. Tanımlı işyerleri varsa isteğe bağlı seçebilirsiniz.'),
 ('Q02',
  'sectors',
  'İşyerinin ana faaliyetleri neler?',
  'multi_sector',
  'Sektörü veya alt faaliyeti seçin. Birden fazla faaliyet eklenebilir; yalnız sektör seçimi bir makinenin bulunduğunu '
  'kanıtlamaz.'),
 ('Q03',
  'areas',
  'Hangi çalışma alanları kapsama girsin?',
  'multi_area',
  'Ofis, depo, üretim gibi alanları seçin. Her alan için ayrı form açılmaz.'),
 ('Q04',
  'equipment',
  'Hangi ekipmanlar kullanılıyor?',
  'multi_equipment',
  'Önerilen ekipmanları seçin veya adıyla arayın. Bu seçim ekipmanın varlığını bildirir; kontrolünün uygun olduğunu '
  'bildirmez.'),
 ('Q05',
  'tasks',
  'Hangi işler yapılıyor?',
  'multi_task',
  'Normal işler, bakım ve özel işleri aynı listeden seçin. Seçmediğiniz iş otomatik olarak yok sayılmaz.'),
 ('Q06',
  'hazards',
  'Hangi özel tehlike veya madde grupları var?',
  'multi_hazard',
  'Örneğin yanıcı sıvı, basınçlı gaz veya kapalı alan. Madde adı ya da miktarı bilinmiyorsa tahmin edilmez.'),
 ('Q07',
  'conditions',
  'Çalışma düzeninde hangileri geçerli?',
  'multi_condition',
  'Gece çalışma, yalnız çalışma, taşeron, ziyaretçi veya tahliye desteği gibi koşulları seçin. Sağlık tanısı '
  'istenmez.'),
 ('Q08',
  'processes',
  'Özel süreçlerden hangileri yapılıyor?',
  'multi_processes',
  'Tank içi çalışma, çözelti hazırlama ve kurutma gibi işlemleri belirtin.'),
 ('Q09',
  'energy',
  'Hangi enerji ve akışkan sistemleri var?',
  'multi_energy',
  'Kullanılan sistemi seçin; basınçlı sistem ve vakum birbirinden ayrılır.'),
 ('Q10',
  'people',
  'Maruz kalan kişiler ve iş düzeni nasıl?',
  'multi_people',
  'Çalışan grupları ve yoğunluğu risk seçimini ayrıntılandırır.'),
 ('Q11',
  'emergency_systems',
  'Acil durumda kritik olan sistemler neler?',
  'multi_emergency_systems',
  'Özel söndürme, havalandırma ve otomasyon sistemlerini belirtin.'),
 ('Q12',
  'method',
  'Hangi risk değerlendirme yöntemini kullanalım?',
  'single_method',
  'Fine–Kinney veya 5×5 matris. Mevcut gerekçeli puan yoksa puan hücreleri düzenlenebilir biçimde boş bırakılır.'),
 ('Q13',
  'preset',
  'Hangi doküman paketini hazırlayalım?',
  'single_preset',
  'Özet, standart veya kapsamlı şablon seçin. İndirme öncesi başka zorunlu soru açılmaz; sütunlar ve sayılar daha '
  'sonra düzenlenebilir.')]

AREAS = {'construction': 'Şantiye',
 'kitchen': 'Mutfak ve yemekhane',
 'laboratory': 'Laboratuvar',
 'office': 'Ofis ve idari alanlar',
 'outdoors': 'Açık saha',
 'plantroom': 'Teknik hacimler',
 'production': 'Üretim alanı',
 'public_area': 'Müşteri/ziyaretçi alanı',
 'remote': 'Evden/uzaktan çalışma',
 'road': 'Saha dışı ulaşım ve teslimat',
 'underground': 'Yeraltı çalışma alanı',
 'warehouse': 'Depo ve sevkiyat',
 'waterfront': 'Su kenarı ve rıhtım',
 'workshop': 'Bakım ve atölye'}

HAZARDS = {'acetylene': 'Asetilen',
 'adjacent_hazard': 'Komşu tesiste büyük kaza tehlikesi',
 'ammonia': 'Amonyak',
 'asbestos': 'Asbest şüphesi',
 'biological': 'Biyolojik etkenler',
 'chlorine': 'Klor',
 'co2': 'CO₂',
 'combustible_dust': 'Yanıcı tozlar',
 'combustion': 'İçten yanmalı motor veya yakıtla çalışan ısıtıcı',
 'compressed_gas': 'Basınçlı gaz tüpleri',
 'confined_space': 'Kapalı alan',
 'corrosives': 'Asit, baz ve korozif maddeler',
 'cryogenic': 'Kriyojenik maddeler',
 'excavation': 'Kazı ve şevler',
 'flammable_liquids': 'Yanıcı sıvılar ve solventler',
 'flood': 'Sel/su baskınına açık konum',
 'forest_interface': 'Orman yangınına açık çevre',
 'h2s': 'Hidrojen sülfür',
 'hazardous_chemicals': 'Diğer tehlikeli kimyasallar',
 'height': 'Yüksekte çalışma',
 'ionizing': 'İyonlaştırıcı radyasyon',
 'landslide': 'Heyelan/şev hareketi',
 'lithium_battery': 'Lityum batarya',
 'lpg': 'LPG',
 'magnetic_field': 'Güçlü manyetik alan/MR',
 'molten_glass': 'Erimiş cam',
 'molten_metal': 'Erimiş metal',
 'natural_gas': 'Doğalgaz',
 'nitrogen': 'Azot/inert gaz',
 'noise': 'Gürültü',
 'oxidizers': 'Oksitleyici maddeler',
 'oxygen': 'Oksijen',
 'peroxide_formers': 'Peroksit oluşturabilen maddeler',
 'polymerizing': 'Polimerleşebilen maddeler',
 'pressure': 'Basınçlı sistemler',
 'pyrophoric': 'Havayla tutuşabilen maddeler',
 'reactive_chemicals': 'Reaktif/kararsız kimyasallar',
 'sensitizers': 'Duyarlılaştırıcı ürünler',
 'silica': 'Silis içeren toz',
 'steam': 'Buhar ve sıcak akışkanlar',
 'water_reactive': 'Suyla tepkime veren maddeler'}

CONDITIONS = {'alone': 'Yalnız çalışma',
 'cold_climate': 'Soğuk ortam',
 'contractor': 'Taşeron/alt işveren',
 'high_workload': 'Yoğun iş ve zaman baskısı',
 'hot_climate': 'Sıcak ortam',
 'language_support': 'Dil/iletişim desteği',
 'mobile_work': 'Seyyar çalışma/teslimat',
 'night': 'Gece/vardiyalı çalışma',
 'pregnancy': 'Gebelik/emzirme için görev uyarlaması',
 'remote_work': 'Uzaktan çalışma',
 'security_exposure': 'Şiddet/güvenlik olayı olasılığı',
 'severe_weather': 'Olumsuz hava koşulları',
 'simops': 'Aynı alanda eşzamanlı işler',
 'support_needs': 'Tahliye veya görev uyarlaması desteği',
 'visitors': 'Ziyaretçi veya müşteri',
 'young': 'Genç çalışan/stajyer'}

PRESETS = {'brief': {'intro': True,
           'label_tr': 'Kısa taslak — 25 madde',
           'legal_topics': True,
           'photo_column': False,
           'residual_columns': False,
           'row_limit': 25,
           'summary_limit': 5},
 'comprehensive': {'intro': True,
                   'label_tr': 'Kapsamlı taslak — en çok 150 madde',
                   'legal_topics': True,
                   'photo_column': True,
                   'residual_columns': True,
                   'row_limit': 150,
                   'summary_limit': 15},
 'sample': {'intro': True,
            'label_tr': 'Örnek taslak — 5 madde (tam değerlendirme değildir)',
            'legal_topics': True,
            'photo_column': False,
            'residual_columns': False,
            'row_limit': 5,
            'summary_limit': 3},
 'standard': {'intro': True,
              'label_tr': 'Standart taslak — 50 madde',
              'legal_topics': True,
              'photo_column': True,
              'residual_columns': True,
              'row_limit': 50,
              'summary_limit': 10}}

FAMILY_NAMES = {'G01': 'Bina, geçiş ve zemin',
 'G02': 'Elektrik',
 'G03': 'Makine güvenliği',
 'G04': 'El aletleri ve taşlama',
 'G05': 'Yüksekte çalışma',
 'G06': 'İskele ve erişim',
 'G07': 'Kaldırma operasyonları',
 'G08': 'Forklift ve iç lojistik',
 'G09': 'Araç ve trafik',
 'G10': 'Depolama',
 'G11': 'Bakım ve enerji izolasyonu',
 'G12': 'Kapalı alan',
 'G13': 'Kazı',
 'G14': 'Yıkım ve asbest',
 'G15': 'Sıcak işler',
 'G16': 'Basınçlı sistemler',
 'G17': 'Gaz tüpleri',
 'G18': 'Kimyasal elleçleme',
 'G19': 'Reaktif prosesler',
 'G20': 'Yangın',
 'G21': 'Patlayıcı atmosfer',
 'G22': 'Toz ve solunum maruziyeti',
 'G23': 'Fiziksel etkenler',
 'G24': 'Ergonomi',
 'G25': 'Biyolojik etkenler',
 'G26': 'İş organizasyonu ve psikososyal etkenler',
 'G27': 'Yetkinlik ve koordinasyon',
 'G28': 'Özel gruplar ve erişilebilirlik',
 'G29': 'Cam üretimi',
 'G30': 'Döküm',
 'G31': 'Metal işleme',
 'G32': 'Ahşap işleme',
 'G33': 'Tekstil',
 'G34': 'Gıda üretimi',
 'G35': 'Sağlık hizmetleri',
 'G36': 'Laboratuvar',
 'G37': 'Tarım',
 'G38': 'Madencilik',
 'G39': 'Enerji tesisleri',
 'G40': 'Atık ve arıtma',
 'G41': 'Konaklama ve hizmet',
 'G42': 'Ofis, eğitim ve teknik bina',
 'G43': 'Yapı işleri',
 'G44': 'Polimer üretimi',
 'G45': 'Basım ve ambalaj',
 'G46': 'Batarya ve elektronik',
 'G47': 'Liman ve deniz işleri',
 'G48': 'Belediye ve açık saha',
 'G49': 'Acil duruma hazırlık',
 'G50': 'Teknik tesis bakımı',
 'G51': 'Ortak güvenlik altyapısı',
 'G52': 'Moto kurye'}

CORE_RISKS = ['R-01-01',
 'R-01-02',
 'R-01-09',
 'R-02-01',
 'R-20-01',
 'R-26-01',
 'R-27-11',
 'R-27-12',
 'R-49-01',
 'R-49-02',
 'R-49-03',
 'R-49-05',
 'R-49-09',
 'R-49-11',
 'R-49-12',
 'R-51-01',
 'R-51-02',
 'R-51-03',
 'R-51-04',
 'R-51-05',
 'R-51-06',
 'R-51-07',
 'R-51-08']

AREA_RISKS = {'construction': ['R-43-01', 'R-43-02', 'R-43-06'],
 'kitchen': ['R-34-05', 'R-34-07', 'R-41-04', 'R-41-05'],
 'laboratory': ['R-36-01', 'R-36-02', 'R-36-04'],
 'office': ['R-24-06', 'R-26-04', 'R-26-11', 'R-26-12', 'R-42-03', 'R-42-07', 'R-42-08', 'R-42-09'],
 'outdoors': ['R-23-06'],
 'plantroom': ['R-02-02', 'R-50-04'],
 'production': ['R-27-10'],
 'public_area': ['R-42-11', 'R-49-05'],
 'remote': ['R-42-12', 'R-24-06', 'R-26-11'],
 'road': ['R-09-02', 'R-09-03', 'R-09-11'],
 'underground': ['R-38-01', 'R-38-02', 'R-38-03'],
 'warehouse': ['R-10-01',
               'R-10-02',
               'R-10-03',
               'R-10-04',
               'R-10-05',
               'R-10-06',
               'R-10-08',
               'R-10-09',
               'R-24-01',
               'R-24-08'],
 'waterfront': ['R-47-01', 'R-47-02', 'R-47-04'],
 'workshop': ['R-04-01', 'R-04-03', 'R-11-01', 'R-11-02']}

CONDITION_RISKS = {'alone': ['R-26-06'],
 'cold_climate': ['R-23-05'],
 'contractor': ['R-27-03', 'R-28-08'],
 'high_workload': ['R-26-01', 'R-26-08', 'R-26-11'],
 'hot_climate': ['R-23-13'],
 'language_support': ['R-27-04', 'R-28-12'],
 'mobile_work': ['R-09-11', 'R-26-08'],
 'night': ['R-26-02', 'R-27-05', 'R-49-07'],
 'pregnancy': ['R-28-02', 'R-28-03'],
 'remote_work': ['R-42-12', 'R-24-06', 'R-26-12'],
 'security_exposure': ['R-26-05'],
 'severe_weather': ['R-09-03'],
 'simops': ['R-27-02'],
 'support_needs': ['R-28-04', 'R-28-05', 'R-28-06'],
 'visitors': ['R-27-08', 'R-49-06'],
 'young': ['R-28-01', 'R-28-07']}

LEAF_REMOVE = {'E041': ['R-27-01'], 'E067': ['R-28-04'], 'S172': ['R-24-10'], 'T122': ['R-09-01'], 'T155': ['R-23-08']}

LEAF_ADD = {'E065': ['R-52-01', 'R-52-02', 'R-52-03', 'R-52-04', 'R-52-05', 'R-52-06', 'R-52-07', 'R-52-08'],
 'T067': ['R-52-01', 'R-52-02', 'R-52-03', 'R-52-04', 'R-52-05', 'R-52-06', 'R-52-07', 'R-52-08']}

RISK_REQUIRE_ANY = {'R-12-02': ['nitrogen'],
 'R-12-03': ['h2s'],
 'R-12-04': ['flammable_liquids'],
 'R-12-05': ['silo_entry'],
 'R-12-07': ['tank_mixer'],
 'R-16-01': ['air_receiver'],
 'R-16-03': ['steam'],
 'R-16-06': ['autoclave'],
 'R-16-07': ['vacuum'],
 'R-16-08': ['hydraulic'],
 'R-16-11': ['boiler'],
 'R-17-02': ['oxygen'],
 'R-17-03': ['lpg'],
 'R-17-04': ['nitrogen'],
 'R-17-05': ['co2', 'server_gas_system'],
 'R-17-06': ['ammonia'],
 'R-17-07': ['chlorine'],
 'R-17-08': ['cryogenic'],
 'R-17-09': ['cryogenic'],
 'R-17-11': ['gas_transport'],
 'R-17-12': ['acetylene'],
 'R-18-01': ['corrosives'],
 'R-18-02': ['flammable_liquids'],
 'R-18-03': ['sensitizers'],
 'R-18-07': ['bulk_chemicals'],
 'R-18-08': ['acid_dilution'],
 'R-18-09': ['cleaning_chemicals'],
 'R-18-10': ['chemical_spraying'],
 'R-19-06': ['peroxide_formers'],
 'R-19-07': ['water_reactive'],
 'R-19-08': ['oxidizers'],
 'R-19-09': ['polymerizing'],
 'R-19-10': ['pyrophoric'],
 'R-20-04': ['kitchen'],
 'R-20-05': ['portable_heater'],
 'R-20-07': ['machinery'],
 'R-20-08': ['flammable_liquids'],
 'R-20-09': ['fire_alarm'],
 'R-20-10': ['sprinkler'],
 'R-20-11': ['fire_water_system'],
 'R-20-12': ['adjacent_hazard'],
 'R-21-01': ['combustible_dust'],
 'R-21-02': ['combustible_dust'],
 'R-21-03': ['flammable_liquids'],
 'R-21-05': ['explosion_vent'],
 'R-21-06': ['combustible_dust'],
 'R-21-07': ['combustible_dust'],
 'R-21-08': ['solvent_dryer'],
 'R-21-09': ['gas_evolving_battery_charge'],
 'R-21-10': ['organic_dust_milling'],
 'R-21-11': ['hot_oil'],
 'R-23-04': ['furnace'],
 'R-23-08': ['stroboscopic_rotating'],
 'R-23-09': ['laser'],
 'R-23-10': ['uv'],
 'R-23-11': ['magnetic_field'],
 'R-23-12': ['ionizing'],
 'R-23-13': ['hot_climate'],
 'R-24-10': ['fine_manual_work'],
 'R-26-10': ['control_room', 'critical_automation', 'process_alarm'],
 'R-26-11': ['high_workload', 'continuous_staffing'],
 'R-26-12': ['remote', 'remote_work'],
 'R-27-01': ['machine_setting'],
 'R-27-02': ['simops'],
 'R-27-04': ['language_support'],
 'R-27-08': ['visitors'],
 'R-28-01': ['young'],
 'R-28-02': ['pregnancy'],
 'R-28-03': ['pregnancy'],
 'R-28-04': ['support_needs'],
 'R-28-05': ['support_needs'],
 'R-28-06': ['support_needs'],
 'R-28-07': ['young', 'new_starter'],
 'R-28-12': ['language_support'],
 'R-42-06': ['server_gas_system'],
 'R-42-12': ['remote', 'remote_work'],
 'R-49-04': ['noise', 'support_needs'],
 'R-49-06': ['visitors', 'contractor'],
 'R-49-08': ['confined_space', 'height', 'waterfront', 'mining'],
 'R-51-09': ['pressure'],
 'R-51-10': ['lifting'],
 'R-51-11': ['changing_required'],
 'R-51-12': ['oed_present']}

FAMILY_FEATURE_GATE = {'G08': ['forklift'],
 'G12': ['confined_space'],
 'G13': ['excavation'],
 'G14': ['demolition', 'asbestos'],
 'G15': ['hot_work'],
 'G16': ['pressure', 'vacuum', 'hydraulic'],
 'G17': ['compressed_gas'],
 'G18': ['hazardous_chemicals', 'corrosives', 'flammable_liquids'],
 'G19': ['reactive_chemicals'],
 'G21': ['combustible_dust',
         'flammable_liquids',
         'lpg',
         'natural_gas',
         'gas_evolving_battery_charge',
         'organic_dust_milling',
         'solvent_dryer'],
 'G29': ['glass'],
 'G30': ['foundry'],
 'G35': ['healthcare'],
 'G36': ['laboratory'],
 'G38': ['mining'],
 'G47': ['waterfront'],
 'G52': ['motorcycle']}

CARD_FEATURES = {'AD-002': ['electrical'],
 'AD-003': ['kitchen'],
 'AD-004': ['flammable_liquids'],
 'AD-005': ['combustible_dust', 'woodworking'],
 'AD-006': ['lithium_battery'],
 'AD-007': ['motorcycle', 'vehicle'],
 'AD-008': ['roof_work', 'hot_work'],
 'AD-009': ['transformer'],
 'AD-010': ['forest_interface'],
 'AD-011': ['explosive_atmosphere', 'reactive_chemicals', 'combustible_dust'],
 'AD-012': ['natural_gas'],
 'AD-013': ['lpg'],
 'AD-014': ['ammonia'],
 'AD-015': ['chlorine'],
 'AD-016': ['nitrogen'],
 'AD-017': ['co2', 'server_gas_system'],
 'AD-018': ['h2s'],
 'AD-019': ['combustion'],
 'AD-020': ['cryogenic'],
 'AD-021': ['hazardous_chemicals', 'corrosives'],
 'AD-022': ['bulk_chemicals', 'reactive_chemicals'],
 'AD-023': ['corrosives'],
 'AD-024': ['reactive_chemicals'],
 'AD-025': ['molten_metal'],
 'AD-026': ['molten_glass'],
 'AD-027': ['steam'],
 'AD-028': ['pressure'],
 'AD-029': ['compressed_gas'],
 'AD-030': ['electrical_work'],
 'AD-031': ['switching_hv'],
 'AD-032': ['machinery'],
 'AD-033': ['lifting'],
 'AD-034': ['height'],
 'AD-035': ['fall_arrest'],
 'AD-036': ['confined_space'],
 'AD-037': ['excavation'],
 'AD-038': ['demolition', 'construction'],
 'AD-040': ['earthquake_damage'],
 'AD-041': ['flood'],
 'AD-042': ['outdoors', 'severe_weather'],
 'AD-043': ['outdoors', 'roof_work'],
 'AD-044': ['hot_climate', 'molten_metal', 'molten_glass'],
 'AD-045': ['cold_climate'],
 'AD-046': ['landslide'],
 'AD-047': ['elevator'],
 'AD-048': ['cold_room'],
 'AD-049': ['critical_power'],
 'AD-050': ['critical_cooling'],
 'AD-051': ['critical_ventilation', 'confined_space'],
 'AD-053': ['high_occupancy', 'bulk_chemicals', 'mining'],
 'AD-054': ['biological', 'healthcare'],
 'AD-055': ['kitchen', 'food_production'],
 'AD-056': ['biological', 'healthcare'],
 'AD-057': ['ionizing'],
 'AD-058': ['magnetic_field'],
 'AD-059': ['waterfront'],
 'AD-060': ['motorcycle', 'vehicle', 'forklift'],
 'AD-061': ['port'],
 'AD-062': ['security_exposure', 'public_area'],
 'AD-063': ['security_exposure'],
 'AD-064': ['security_exposure'],
 'AD-065': ['adjacent_hazard'],
 'AD-066': ['adjacent_hazard'],
 'AD-067': ['bulk_chemicals', 'hazardous_chemicals'],
 'AD-068': ['fire_system_outage'],
 'AD-070': ['support_needs'],
 'AD-071': ['mining'],
 'AD-072': ['critical_automation']}

CORE_CARDS = ['AD-001', 'AD-039', 'AD-052', 'AD-069']

MODES = {'CONTROLLED_SHUTDOWN': 'Yetkili kontrollü durdurma',
 'EVACUATE': 'Güvenli tahliye',
 'LOCAL_ISOLATION': 'Yerel alanı ayırma',
 'MEDICAL_RESPONSE': 'İlkyardımcı ve acil sağlık desteği',
 'PROTECT_THEN_EVACUATE': 'Önce korunma, sarsıntı bitince güvenli tahliye',
 'SECURITY_PROTECTION': 'Güvenlik olayında korunma',
 'SHELTER_IN_PLACE': 'Güvenli yerde korunma',
 'SPECIALIST_RESPONSE': 'Uzman müdahalesi/kurtarma'}

LEAF_FEATURES = {'E001': ['electrical'],
 'E002': ['transformer', 'electrical'],
 'E003': ['combustion', 'electrical', 'critical_power'],
 'E004': ['critical_power'],
 'E006': ['fire_alarm'],
 'E007': ['fire_door'],
 'E011': ['height'],
 'E012': ['height'],
 'E013': ['height'],
 'E014': ['height'],
 'E015': ['height'],
 'E016': ['height'],
 'E017': ['height'],
 'E018': ['height'],
 'E019': ['height'],
 'E020': ['height'],
 'E021': ['lifting'],
 'E022': ['lifting'],
 'E023': ['lifting'],
 'E024': ['lifting'],
 'E025': ['lifting'],
 'E026': ['lifting'],
 'E027': ['lifting'],
 'E028': ['lifting'],
 'E029': ['lifting'],
 'E030': ['lifting'],
 'E031': ['lifting'],
 'E032': ['lifting'],
 'E033': ['lifting'],
 'E034': ['lifting'],
 'E035': ['lifting'],
 'E036': ['lifting'],
 'E037': ['lifting'],
 'E038': ['lifting'],
 'E039': ['lifting'],
 'E041': ['forklift', 'lifting', 'vehicle'],
 'E042': ['forklift', 'lifting', 'vehicle'],
 'E043': ['forklift', 'lifting', 'vehicle'],
 'E045': ['lifting', 'vehicle'],
 'E046': ['lifting', 'vehicle'],
 'E047': ['lifting', 'vehicle'],
 'E061': ['vehicle'],
 'E062': ['vehicle'],
 'E063': ['vehicle'],
 'E064': ['vehicle'],
 'E065': ['motorcycle', 'vehicle'],
 'E066': ['vehicle'],
 'E067': ['vehicle'],
 'E068': ['vehicle'],
 'E069': ['vehicle'],
 'E070': ['vehicle'],
 'E071': ['vehicle'],
 'E072': ['vehicle'],
 'E073': ['vehicle'],
 'E074': ['vehicle'],
 'E075': ['vehicle'],
 'E076': ['vehicle'],
 'E077': ['vehicle'],
 'E078': ['vehicle'],
 'E079': ['vehicle'],
 'E080': ['vehicle'],
 'E081': ['machinery'],
 'E082': ['machinery'],
 'E083': ['machinery'],
 'E084': ['machinery'],
 'E085': ['machinery'],
 'E086': ['machinery'],
 'E087': ['machinery'],
 'E088': ['machinery'],
 'E089': ['machinery'],
 'E090': ['machinery'],
 'E091': ['machinery', 'hydraulic'],
 'E092': ['machinery'],
 'E093': ['machinery'],
 'E094': ['machinery'],
 'E095': ['machinery'],
 'E096': ['machinery'],
 'E097': ['machinery'],
 'E098': ['machinery'],
 'E099': ['laser', 'machinery'],
 'E100': ['machinery'],
 'E111': ['hot_work'],
 'E112': ['hot_work'],
 'E113': ['hot_work'],
 'E114': ['hot_work'],
 'E115': ['hot_work'],
 'E118': ['chemical_spraying', 'flammable_liquids'],
 'E119': ['corrosives'],
 'E120': ['furnace'],
 'E121': ['pressure'],
 'E122': ['air_receiver', 'pressure'],
 'E123': ['boiler', 'pressure', 'steam'],
 'E124': ['hot_oil', 'pressure'],
 'E125': ['pressure'],
 'E127': ['autoclave', 'pressure'],
 'E128': ['vacuum'],
 'E129': ['pressure'],
 'E131': ['compressed_gas', 'oxygen'],
 'E132': ['compressed_gas', 'acetylene'],
 'E133': ['compressed_gas', 'nitrogen'],
 'E134': ['co2', 'compressed_gas'],
 'E135': ['compressed_gas', 'lpg'],
 'E136': ['cryogenic'],
 'E137': ['ammonia', 'pressure'],
 'E141': ['reactive_chemicals', 'hazardous_chemicals', 'machinery'],
 'E143': ['hazardous_chemicals', 'bulk_chemicals'],
 'E151': ['dust_collector'],
 'E153': ['explosion_vent', 'explosive_atmosphere'],
 'E154': ['explosive_atmosphere'],
 'E161': ['glass', 'molten_glass', 'furnace', 'critical_cooling'],
 'E162': ['glass', 'machinery'],
 'E163': ['glass', 'molten_glass', 'machinery'],
 'E164': ['furnace'],
 'E165': ['glass'],
 'E166': ['glass'],
 'E167': ['glass', 'machinery'],
 'E168': ['glass', 'furnace'],
 'E169': ['glass', 'machinery'],
 'E170': ['glass', 'machinery'],
 'E171': ['foundry', 'molten_metal', 'furnace'],
 'E172': ['foundry', 'molten_metal', 'furnace'],
 'E173': ['foundry', 'molten_metal'],
 'E174': ['foundry', 'molten_metal'],
 'E180': ['foundry', 'molten_metal'],
 'E181': ['machinery', 'woodworking'],
 'E182': ['machinery', 'woodworking'],
 'E183': ['machinery', 'woodworking'],
 'E184': ['machinery', 'woodworking'],
 'E185': ['machinery', 'woodworking'],
 'E186': ['machinery', 'woodworking'],
 'E187': ['machinery', 'woodworking'],
 'E188': ['machinery', 'woodworking'],
 'E189': ['machinery', 'woodworking'],
 'E190': ['machinery', 'woodworking'],
 'E191': ['machinery'],
 'E192': ['machinery'],
 'E193': ['machinery'],
 'E194': ['machinery'],
 'E195': ['machinery'],
 'E196': ['machinery'],
 'E197': ['machinery'],
 'E198': ['machinery'],
 'E199': ['machinery'],
 'E200': ['machinery'],
 'E201': ['food_production', 'machinery'],
 'E202': ['food_production', 'machinery'],
 'E203': ['food_production', 'machinery'],
 'E204': ['food_production', 'machinery'],
 'E205': ['food_production', 'kitchen', 'machinery'],
 'E206': ['food_production', 'machinery'],
 'E207': ['food_production', 'machinery'],
 'E208': ['food_production', 'machinery'],
 'E209': ['food_production', 'machinery'],
 'E210': ['cold_room', 'cold_climate'],
 'E211': ['machinery'],
 'E212': ['machinery'],
 'E213': ['machinery'],
 'E214': ['machinery'],
 'E215': ['machinery'],
 'E216': ['machinery'],
 'E217': ['machinery'],
 'E218': ['machinery'],
 'E219': ['machinery'],
 'E220': ['machinery'],
 'E221': ['machinery'],
 'E222': ['machinery'],
 'E223': ['machinery', 'uv'],
 'E224': ['machinery'],
 'E225': ['machinery'],
 'E226': ['machinery'],
 'E227': ['machinery'],
 'E228': ['machinery'],
 'E229': ['machinery'],
 'E230': ['machinery'],
 'E231': ['magnetic_field', 'healthcare', 'cryogenic'],
 'E232': ['ionizing', 'healthcare'],
 'E233': ['ionizing', 'healthcare'],
 'E235': ['healthcare', 'lifting'],
 'E236': ['healthcare'],
 'E238': ['biological', 'laboratory'],
 'E239': ['healthcare', 'hazardous_chemicals'],
 'E240': ['healthcare', 'compressed_gas'],
 'E241': ['laboratory'],
 'E242': ['laboratory'],
 'E243': ['laboratory'],
 'E244': ['laboratory'],
 'E245': ['laboratory', 'uv'],
 'E246': ['laboratory'],
 'E247': ['laboratory'],
 'E248': ['laboratory'],
 'E249': ['laboratory'],
 'E250': ['cryogenic', 'laboratory'],
 'E261': ['machinery', 'mining'],
 'E262': ['machinery', 'mining'],
 'E263': ['machinery', 'mining'],
 'E264': ['machinery', 'mining'],
 'E265': ['machinery', 'mining'],
 'E266': ['machinery', 'mining'],
 'E267': ['machinery', 'mining'],
 'E268': ['machinery', 'mining'],
 'E269': ['machinery', 'mining'],
 'E270': ['machinery', 'mining'],
 'E275': ['biological', 'h2s', 'explosive_atmosphere'],
 'E276': ['pressure', 'h2s'],
 'E277': ['lithium_battery'],
 'E278': ['lithium_battery'],
 'E279': ['lithium_battery', 'critical_power'],
 'E280': ['lifting', 'electrical_work'],
 'E291': ['port', 'waterfront', 'lifting'],
 'E292': ['waterfront'],
 'E293': ['waterfront', 'machinery'],
 'E294': ['waterfront'],
 'E295': ['flammable_liquids'],
 'E296': ['elevator'],
 'E298': ['biological'],
 'E300': ['fire_water_system'],
 'S013': ['mining'],
 'S014': ['mining'],
 'S015': ['mining'],
 'S016': ['mining'],
 'S017': ['mining'],
 'S018': ['mining'],
 'S019': ['construction'],
 'S020': ['construction'],
 'S021': ['construction'],
 'S022': ['construction'],
 'S023': ['construction'],
 'S024': ['construction'],
 'S025': ['construction'],
 'S026': ['construction'],
 'S027': ['construction'],
 'S028': ['construction'],
 'S029': ['construction'],
 'S030': ['construction'],
 'S031': ['construction'],
 'S032': ['construction'],
 'S033': ['construction'],
 'S034': ['construction'],
 'S035': ['construction'],
 'S036': ['construction'],
 'S037': ['glass', 'molten_glass', 'furnace'],
 'S038': ['glass', 'molten_glass', 'furnace'],
 'S039': ['glass', 'molten_glass', 'furnace'],
 'S040': ['glass'],
 'S041': ['glass', 'furnace'],
 'S042': ['glass'],
 'S046': ['foundry'],
 'S047': ['foundry'],
 'S048': ['foundry'],
 'S049': ['foundry'],
 'S064': ['hazardous_chemicals'],
 'S065': ['hazardous_chemicals'],
 'S066': ['hazardous_chemicals'],
 'S067': ['hazardous_chemicals'],
 'S068': ['hazardous_chemicals'],
 'S082': ['woodworking'],
 'S083': ['woodworking'],
 'S084': ['woodworking'],
 'S085': ['woodworking'],
 'S091': ['food_production'],
 'S092': ['food_production'],
 'S093': ['food_production'],
 'S094': ['food_production'],
 'S095': ['food_production'],
 'S096': ['food_production'],
 'S097': ['cold_climate', 'cold_room', 'food_production'],
 'S098': ['food_production'],
 'S099': ['food_production'],
 'S100': ['food_production'],
 'S101': ['food_production'],
 'S102': ['food_production'],
 'S103': ['food_production'],
 'S104': ['food_production'],
 'S105': ['food_production'],
 'S106': ['food_production'],
 'S107': ['food_production'],
 'S108': ['food_production', 'kitchen'],
 'S129': ['hazardous_chemicals', 'bulk_chemicals'],
 'S132': ['mobile_work', 'vehicle'],
 'S133': ['port', 'waterfront'],
 'S140': ['lpg', 'compressed_gas'],
 'S145': ['healthcare'],
 'S146': ['healthcare'],
 'S147': ['healthcare'],
 'S148': ['healthcare', 'laboratory', 'biological'],
 'S149': ['healthcare'],
 'S150': ['healthcare'],
 'S151': ['healthcare'],
 'S152': ['biological'],
 'S159': ['laboratory'],
 'S163': ['public_area'],
 'S164': ['kitchen'],
 'S165': ['kitchen'],
 'S166': ['kitchen'],
 'S169': ['public_area'],
 'S172': ['office'],
 'S173': ['office'],
 'S174': ['office', 'public_area'],
 'S175': ['office', 'public_area'],
 'S178': ['outdoors'],
 'S180': ['outdoors', 'biological'],
 'T007': ['night', 'alone'],
 'T009': ['electrical_work'],
 'T010': ['electrical_work'],
 'T011': ['electrical_work'],
 'T012': ['electrical_work'],
 'T013': ['electrical_work'],
 'T014': ['electrical_work'],
 'T015': ['electrical_work'],
 'T016': ['electrical_work'],
 'T017': ['machinery'],
 'T018': ['machine_setting', 'machinery'],
 'T019': ['machinery'],
 'T020': ['machinery'],
 'T021': ['machinery'],
 'T022': ['machinery'],
 'T023': ['machinery'],
 'T024': ['machinery'],
 'T033': ['height', 'roof_work'],
 'T034': ['height'],
 'T035': ['height'],
 'T036': ['fall_arrest', 'height'],
 'T037': ['fall_arrest', 'height'],
 'T038': ['height'],
 'T039': ['fall_arrest', 'height'],
 'T040': ['height'],
 'T041': ['height'],
 'T042': ['height'],
 'T043': ['height'],
 'T044': ['height'],
 'T045': ['height'],
 'T046': ['height'],
 'T047': ['height'],
 'T048': ['height'],
 'T049': ['lifting'],
 'T050': ['lifting'],
 'T051': ['lifting'],
 'T052': ['lifting'],
 'T053': ['lifting'],
 'T054': ['lifting'],
 'T055': ['lifting'],
 'T056': ['lifting'],
 'T057': ['forklift', 'lifting', 'vehicle'],
 'T058': ['forklift', 'lifting', 'vehicle'],
 'T065': ['vehicle'],
 'T066': ['vehicle'],
 'T067': ['mobile_work', 'motorcycle', 'vehicle'],
 'T068': ['vehicle'],
 'T069': ['reversing', 'vehicle'],
 'T070': ['vehicle'],
 'T071': ['vehicle'],
 'T072': ['vehicle'],
 'T080': ['cold_climate', 'cold_room'],
 'T089': ['confined_space'],
 'T090': ['confined_space', 'silo_entry'],
 'T091': ['confined_space', 'h2s'],
 'T092': ['confined_space'],
 'T093': ['confined_space'],
 'T094': ['confined_space'],
 'T095': ['confined_space'],
 'T096': ['confined_space'],
 'T097': ['excavation'],
 'T098': ['excavation'],
 'T099': ['excavation'],
 'T100': ['excavation'],
 'T101': ['excavation'],
 'T102': ['excavation'],
 'T103': ['excavation'],
 'T104': ['excavation'],
 'T105': ['demolition'],
 'T106': ['demolition'],
 'T107': ['asbestos', 'demolition'],
 'T108': ['demolition'],
 'T109': ['demolition'],
 'T110': ['demolition'],
 'T111': ['demolition'],
 'T112': ['demolition'],
 'T113': ['hot_work'],
 'T114': ['hot_work'],
 'T115': ['hot_work'],
 'T116': ['hot_work'],
 'T117': ['hot_work'],
 'T118': ['hot_work'],
 'T119': ['hot_work'],
 'T120': ['compressed_gas', 'hot_work'],
 'T122': ['pressure'],
 'T123': ['pressure'],
 'T124': ['steam', 'pressure'],
 'T125': ['autoclave', 'pressure'],
 'T126': ['vacuum'],
 'T129': ['compressed_gas', 'gas_transport'],
 'T130': ['compressed_gas'],
 'T131': ['lpg', 'compressed_gas'],
 'T132': ['cryogenic'],
 'T133': ['nitrogen'],
 'T134': ['ammonia', 'pressure'],
 'T135': ['chlorine'],
 'T137': ['hazardous_chemicals'],
 'T138': ['hazardous_chemicals'],
 'T139': ['hazardous_chemicals'],
 'T140': ['hazardous_chemicals', 'reactive_chemicals'],
 'T141': ['flammable_liquids', 'hazardous_chemicals'],
 'T142': ['bulk_chemicals', 'hazardous_chemicals'],
 'T143': ['hazardous_chemicals'],
 'T144': ['hazardous_chemicals'],
 'T145': ['flammable_liquids'],
 'T146': ['explosive_atmosphere'],
 'T148': ['combustible_dust'],
 'T149': ['fire_system_outage'],
 'T151': ['fire_water_system'],
 'T152': ['explosive_atmosphere'],
 'T155': ['noise'],
 'T157': ['hot_climate'],
 'T158': ['cold_climate'],
 'T160': ['fine_manual_work'],
 'T161': ['glass'],
 'T162': ['glass', 'molten_glass'],
 'T163': ['glass'],
 'T164': ['glass', 'furnace'],
 'T165': ['foundry', 'molten_metal'],
 'T166': ['foundry', 'molten_metal'],
 'T174': ['hazardous_chemicals'],
 'T180': ['cleaning_chemicals'],
 'T181': ['kitchen', 'food_production'],
 'T182': ['co2', 'food_production'],
 'T183': ['cold_room', 'cold_climate'],
 'T185': ['healthcare', 'biological'],
 'T186': ['healthcare'],
 'T187': ['healthcare', 'hazardous_chemicals'],
 'T188': ['magnetic_field', 'healthcare'],
 'T191': ['biological', 'laboratory'],
 'T192': ['biological', 'healthcare'],
 'T193': ['laboratory'],
 'T194': ['laboratory'],
 'T195': ['laboratory', 'reactive_chemicals'],
 'T196': ['cryogenic', 'laboratory'],
 'T197': ['laboratory', 'pressure'],
 'T198': ['laboratory'],
 'T199': ['laboratory'],
 'T200': ['laboratory'],
 'T202': ['chemical_spraying', 'hazardous_chemicals'],
 'T205': ['mining'],
 'T206': ['mining'],
 'T207': ['mining'],
 'T208': ['explosive_atmosphere', 'mining'],
 'T212': ['h2s', 'biological', 'explosive_atmosphere'],
 'T226': ['kitchen'],
 'T227': ['hazardous_chemicals'],
 'T231': ['chemical_spraying'],
 'T233': ['waterfront'],
 'T234': ['waterfront'],
 'T235': ['confined_space', 'waterfront'],
 'T236': ['lifting', 'port', 'waterfront'],
 'T239': ['elevator', 'height'],
 'T240': ['machinery']}

HAZARD_FAMILY_RISKS = {'asbestos': ['G14'],
 'biological': ['G25'],
 'combustible_dust': ['G21'],
 'compressed_gas': ['G17'],
 'confined_space': ['G12'],
 'corrosives': ['G18'],
 'excavation': ['G13'],
 'flammable_liquids': ['G18', 'G20', 'G21'],
 'hazardous_chemicals': ['G18'],
 'height': ['G05'],
 'molten_glass': ['G29'],
 'molten_metal': ['G30'],
 'pressure': ['G16'],
 'reactive_chemicals': ['G19'],
 'silica': ['G22']}

